apps/proyecto/urls.py
from django.conf.urls import url
from apps.proyecto.views import create_disenos, producto_edit, pru, proyecto_view, proyecto_home, proyecto_list,proyecto_edit, inicio, producto_proyecto, solicitud
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^$', login_required(proyecto_view), name='proyecto_view'),
	url(r'^home/', login_required(proyecto_home), name='proyecto_home'),
	url(r'^list$', login_required(proyecto_list), name='proyecto_list'),
	url(r'^editar/(?P<id_proyecto>\d+)/$', login_required(proyecto_edit), name='proyecto_edit'),
	url(r'^inicio/', login_required(inicio), name='inicio'),
	url(r'^prueba/$', login_required(producto_proyecto), name='producto_proyecto'),
	url(r'^pru/(?P<id_proyecto>\d+)/(?P<id_producto>\d+)/$', login_required(pru), name='pru'),
	url(r'^ediproducto/(?P<id_producto>\d+)/$', login_required(producto_edit), name='producto_edit'),
	url(r'^solicitarcliente/$', login_required(solicitud), name='solicitud'),
	url(r'^diseños/$', login_required(create_disenos), name='create_disenos'),
]

intigroup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^adminInti/', admin.site.urls),
    url(r'^proyecto/', include('apps.proyecto.urls', namespace="pyc")),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usu")),
    url(r'^diseno/', include('apps.diseno.urls', namespace="dis")),
    url(r'^$', login, {'template_name':'index.html'}, name="login"),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout', logout_then_login, name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/proyecto/models.py
from django.db import models
from django.contrib.auth.models import User

prueba = (('FR', 'Freshman'),('b', 'b'))

# Create your models here.
class cliente(models.Model):
	nit = models.IntegerField()
	nombre = models.CharField(max_length=125)
	telefono = models.IntegerField(blank=True, null=True)
	contacto = models.CharField(max_length=125, blank=True, null=True)
	correo = models.EmailField(max_length=125, blank=True, null=True)
	cargo = models.CharField(max_length=125, blank=True, null=True)

	def __str__(self):
		return	self.nombre

class tipoProyecto(models.Model):
	codigo = models.IntegerField()
	nombre = models.CharField(max_length=125)

	def __str__(self):
		return self.nombre

class opcionesD(models.Model):
	nombre = models.CharField(max_length=30)

	def __str__(self):
		return self.nombre

class proyecto(models.Model):
	nombreCliente = models.ForeignKey(cliente, null=True, blank=True, on_delete=models.CASCADE)
	nitCliente = models.IntegerField()
	asesor = models.ForeignKey(User, on_delete=models.CASCADE, default=User)
	fecha = models.DateField(auto_now_add=True)
	valor = models.IntegerField(default=0)
	descripcion = models.CharField(max_length=125)
	descripcionP = models.TextField(max_length=125, null=True, blank=True)
	tipoProyecto = models.ForeignKey(tipoProyecto, on_delete=models.CASCADE, null=True, blank=True)
	fechaEntDis = models.DateField(auto_now_add=False, blank=True, null=True)
	fechaMueFis = models.DateField(auto_now_add=False, blank=True, null=True)
	fechaApr = models.DateField(auto_now_add=False, blank=True, null=True)
	fechaEntPro = models.DateField(auto_now_add=False, blank=True, null=True)
	descripcionF = models.TextField(max_length=125, null=True, blank=True)
	selec = models.ManyToManyField(opcionesD, blank=True)

	def __str__(self):
		return self.descripcion

class item(models.Model):
	padre = models.CharField(max_length=60)
	hijo = models.CharField(max_length=60)
	ruta = models.CharField(max_length=60)
	font = models.CharField(max_length=60, blank=True, null=True)

	def __str__(self):
		return self.padre

class imgpyc(models.Model):
	proyecto = models.CharField(max_length=4, blank=True, null=True)
	document = models.FileField(upload_to='imagenesProyecto/')
	uploaded_at = models.DateTimeField(auto_now_add=True)

apps/proyecto/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from apps.proyecto.models import proyecto, imgpyc

class ProyectoForm(forms.ModelForm):

	class Meta:
		model = proyecto

		fields = ('nombreCliente', 'nitCliente', 'asesor', 'valor','descripcion','descripcionP', 'tipoProyecto', 'fechaEntDis', 'fechaMueFis', 'fechaApr', 'fechaEntPro', 'descripcionF', 'selec')
		widgets = {
			'nombreCliente': forms.Select(attrs = {'class':'form-control','readonly':'readonly'}),
			'nitCliente': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nit Cliente'}),
			'asesor': forms.Select(attrs = {'class':'form-control','readonly':'readonly'}),
			'valor': forms.TextInput(attrs = {'class': 'form-control'}),
			'descripcion': forms.TextInput(attrs = {'class': 'form-control', 'placeholder':'Titulo del proyecto'}),
			'descripcionP':forms.Textarea(attrs = {'class': 'form-control wysihtml5'}), #wysihtml5
			'tipoProyecto': forms.Select(attrs = {'class':'form-control'}),
			'fechaEntDis': forms.TextInput(attrs={'class':'form-control datepicker','readonly':'readonly'}),
			'fechaMueFis': forms.TextInput(attrs={'class':'form-control datepicker','readonly':'readonly'}),
			'fechaApr': forms.TextInput(attrs={'class':'form-control datepicker','readonly':'readonly'}),
			'fechaEntPro': forms.TextInput(attrs={'class':'form-control datepicker','readonly':'readonly'}),
			'descripcionF':forms.Textarea(attrs = {'class': 'form-control wysihtml5'}),
			'selec': forms.CheckboxSelectMultiple({'class':'form-control col-md-9'}),
		}

class ImagenesPYCForm(forms.ModelForm):
	class Meta:
		model = imgpyc

		fields = ('proyecto', 'document')

apps/proyecto/views.py
from django.shortcuts import render
from django.http import HttpResponse
from apps.proyecto.models import item
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from apps.proyecto.models import proyecto, cliente
from apps.proyecto.forms import ProyectoForm, ImagenesPYCForm
import time
from django.shortcuts import redirect
from apps.diseno.forms import productoForm, disenoForm
from apps.diseno.models import producto, diseno
from datetime import datetime,timedelta, date

#variables publicas
i = item.objects.all()
f = time.strftime("%d/%m/%y")


# Vistas PROYECTO

#Creación de proyectos
def proyecto_view(request):
	client = cliente.objects.all()
	if request.method == 'POST':
		print('ingreso')
		# create a form instance and populate it with data from the request:
		form = ProyectoForm(request.POST)
		# check whether it's valid:
		print   ("siii")
		if form.is_valid():
			id_proyecto = form.save()
		return redirect('pyc:proyecto_edit', id_proyecto.id)
	else:
		form = ProyectoForm()

	return render(request, 'proyecto/index.html', {'i':i, 'form':form, 'f':f, 'client':client})

#creación de producto
def producto_proyecto(request):
	if request.method == 'POST':
		print('ingreso')
		# create a form instance and populate it with data from the request:
		form = productoForm(request.POST)
		# check whether it's valid:
		print   ("siii")
		if form.is_valid():
			if form.cleaned_data['nombre'] == '':
				print ('nombre vacio')
			else:

				form.idProyecto = form.cleaned_data['idProyecto']
				form.nombre = form.cleaned_data['nombre']
				id_producto = form.save()
				return redirect('pyc:producto_edit', id_producto.id)
			return HttpResponse("Error!!!")
	else:
		return HttpResponse("Error!!!")

	return render(request, 'proyecto/index.html', {'i':i, 'f':f})


#edicción de productos
def producto_edit(request, id_producto):
	dise = diseno.objects.filter(idProducto=id_producto)
	product =  producto.objects.get(id=id_producto)
	disForm = disenoForm()
	if request.method == 'GET':
		form = productoForm(instance=product)	
	else:
		form = productoForm(request.POST, instance=product)
		if form.is_valid():
			form.save()
	return render(request, 'proyecto/editprod.html', {'form':form, 'i':i, 'product':product, 'dise':dise, 'disForm':disForm})


#Primera vista despues del login
def proyecto_home(request):
	return render(request, 'base/base.html', {'i':i})

#lista de proyectos
def proyecto_list(request):
	p = proyecto.objects.all()
	ar = []
	h = date.today() 
	for x in p:
		a = x.fecha
		dias = a+timedelta(days=2)
		ar.append(dias<=h)
		print(ar)
	return render(request, 'proyecto/list.html', {'i':i, 'p':p})

#edicción de proyectos
def proyecto_edit(request, id_proyecto):
	# if request.user.is_authenticated:
	# 	print("authenticado")
	# else:
	# 	print("Negativo")
	prod = producto.objects.filter(idProyecto=id_proyecto)
	print(prod)
	proyect =  proyecto.objects.get(id=id_proyecto)
	a = id_proyecto
	b = proyecto.objects.filter(id=id_proyecto)
	fe = ''
	for s in b:
		fe = s.fecha
	print(request.user.is_authenticated)
	if request.method == 'GET':
		form = ProyectoForm(instance=proyect)
		imgPyc = ImagenesPYCForm()
	else:
		form = ProyectoForm(request.POST, instance=proyect)
		if form.is_valid():
			form.save()
	if request.method == 'POST':
		imgPyc = ImagenesPYCForm(request.POST, request.FILES)
		if imgPyc.is_valid():
			print("formulario imgpyc")
		return redirect('pyc:proyecto_list')
	return render(request, 'proyecto/editpyc.html', {'form':form,'i':i,'a':a, 'fe': fe, 'imgPyc':imgPyc, 'prod':prod})

#Vista inicial de Matrícula de proyectos
def inicio(request):
	pyc=proyecto.objects.all()
	c = pyc.count()
	return render(request, 'proyecto/inicio.html', {'i':i, 'c':c})

#prueba
def pru(request, id_proyecto, id_producto):
	print(id_proyecto)
	print(id_producto)
	return HttpResponse("prueba")

#Creación solicitud de clientes
def solicitud(request):
	return render(request, 'proyecto/SolicitudCliente.html', {'i':i})

#Creación diseños
def create_disenos(request):
	print('entro al diseno')
	if request.method == 'POST':
		form = disenoForm(request.POST)
		if form.is_valid():
			f = form.save()
			return redirect('proyecto_list')
	return HttpResponse('prueba2')

templates/proyecto/SolicitudCliente.html
{% extends 'base/base.html' %}

{% block principal %}

<div class="panel panel-primary" data-collapsed="0">
    <div class="panel-heading" >
        <div class="panel-title">
            Solicitud nuevo cliente
        </div>  
    </div>
    <div class="panel-body">

        <form method="post" role="form" class="form-horizontal form-groups-bordered">{% csrf_token %}
        
            <div class="row">
                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Nombre del cliente</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Nombre del cliente">
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Razón social</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Razón social">
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Nit</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Nit">
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Correo</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Correo">
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Teléfono</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Teléfono">
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Solicitante</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Solicitante" disabled>
                    </div>
                </div>

                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Observaciones</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="nombre" placeholder="Observaciones">
                    </div>
                </div>  

			<div class="col-md-11"></div>
			<div class="col-md-1">
            <button type="submit" class="btn btn-default btn-icon icon-left" >
                Guardar
                <i class="entypo-floppy"></i>
            </button>
            </div>
                                      
    		</div>
		</div>
</form>
</div>

{% endblock %}

templates/proyecto/asignardiseño.html
{% extends 'base/base.html' %}

{% block principal %}
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

templates/proyecto/index.html
{% extends 'base/base.html' %}

{% block principal %}
<div class="panel panel-primary" data-collapsed="0">
	<div class="panel-heading" >
		<div class="panel-title">
            Información general
		</div>	
		
        <div class="panel-options align-middle">
            <div class="row">
                <div class="col-md-4">	
                    <button type="button" class="btn btn-default btn-icon icon-left" onclick="">
                        Guardar
                        <i class="entypo-floppy"></i>
                    </button>
                </div>
                <div class="col-md-4">	
                    <button type="button" class="btn btn-default btn-icon icon-left" onclick="">
                        Limpiar
                        <i class="entypo-doc"></i>
                    </button>
                </div>
                <div class="col-md-4">	
                    <button id="btnListar" type="button" class="btn btn-default btn-icon icon-left" onclick="">
                        Listar
                        <i class="entypo-print"></i>
                    </button>
                </div>
            </div>
	    </div>
    </div>
	<div class="panel-body">

        <form method="post" role="form" class="form-horizontal form-groups-bordered">{% csrf_token %}

            <div class="row">
                <div class="form-group">
                    <label for="idproyecto" class="col-md-2 control-label">Id Proyecto</label>   
                    <div class="col-md-9 input-group">
                        <input type="text" class="form-control" id="idproyecto" placeholder="Proyecto nuevo"   disabled>
                    </div>
                </div>

                <div class="form-group">
                    <label for="nitcliente" class="col-md-2 control-label">Cliente</label>
                    <div class="col-md-3 input-group">
                        {{ form.nitCliente }}
                        <div class="input-group-btn">
                            <button type="button" id="btnCargarCliente" class="btn btn-primary" aria-label="Help"><span class="glyphicon glyphicon-retweet"></span></button>
                        </div>
                    </div>

                    <div class="col-md-6 input-group">
                        {{ form.nombreCliente }}
                        <div class="input-group-btn">
                            <button type="button" id="btnBuscarCliente" class="btn btn-primary" aria-label="Help" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-search"></span></button>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="txtAsesor" class="col-md-2 control-label">Asesor</label>
                    <div class="col-md-9">
                         {{ form.asesor }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="txtFechaProy" class="col-md-2 control-label">Fecha</label>
                    <div class="input-group col-md-9">
                        <input type="text" class="form-control datepicker" id="txtFechaProy" data-start-view="1" value="{{f}}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="txtNombre" class="col-md-2 control-label">Nombre</label>
                    <div class="col-md-9">
                        {{ form.descripcion }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="txtValor" class="col-md-2 control-label">Valor</label>
                    <div class="col-md-9 input-group">
                        <span class="input-group-addon">$</span>                        
                        {{ form.valor }}
                    </div>
                </div>
                <i class="fa fa-usd"></i>
            </div>
            <input type="submit" value="Guardar" />
        </form>
	</div>
</div>

<!-- Trigger the modal with a button 
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" aria-label="Help"><span class="glyphicon glyphicon-flash"></span></button>-->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Seleccionar un cliente</h4>
      </div>
      <div class="modal-body">
        <table id="example" class="table table-hover dataTable">
            <thead>
                <tr>
                    <th>Nit</th>
                    <th>Nombre Cliente</th>
                    <th>Contacto</th>
                    <th>Correo</th>
                    <th>Teléfono</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Nit</th>
                    <th>Nombre Cliente</th>
                    <th>Contacto</th>
                    <th>Correo</th>
                    <th>Teléfono</th>
                </tr>
            </tfoot>
            <tbody>
            {% for cliente in client %}  
            <tr> 
                <td><a href="">{{cliente.nit}}</a></td>
                <td>{{cliente.nombre}}</td>
                <td>{{cliente.contacto}}</td>
                <td>{{cliente.correo}}</td>
                <td>{{cliente.telefono}}</td>
            </tr> 
            {% endfor %}
        </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>
</div>

{% endblock %}
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

templates/proyecto/inicio.html
{% extends 'base/base.html' %}

{% block principal %}
		<div class="row">
			<a href="{% url 'pyc:proyecto_list' %}">
			<div class="col-sm-3 col-xs-6">
		
				<div class="tile-stats tile-primary">
					<div class="icon"><i class="entypo-clipboard"></i></div>
					<div class="num" data-start="0" data-end="{{c}}" data-postfix="" data-duration="2500" data-delay="0">0</div>
		
					<h3>Ver Proyectos</h3>
					<p>Se visualizan todos los proyectos creados</p>
				</div>
		
			</div>
			</a>
			
			<a href="{% url 'pyc:proyecto_view' %}">
			<div class="col-sm-3 col-xs-6">
		
				<div class="tile-stats tile-blue">
					<div class="icon"><i class="entypo-list-add"></i></div>
					<div class="num" data-start="0" data-end="{{c}}" data-postfix="" data-duration="1500" data-delay="600">0</div>
		
					<h3>Crear Proyectos</h3>
					<p>Permite la edición de proyectos creados.</p>
				</div>
		
			</div>
			</a>
			
			<a href="{% url 'pyc:solicitud' %}">
			<div class="col-sm-3 col-xs-6">
		
				<div class="tile-stats tile-green">
					<div class="icon"><i class="entypo-mail"></i></div>
					<div class="num" data-start="0" data-end="5" data-postfix="" data-duration="1500" data-delay="1200">0</div>
		
					<h3>Solicitud Nuevo Cliente</h3>
					<p>Nuevo cliente.</p>
				</div>
			</div>
			</a>
		</div>
{% endblock %}

templates/proyecto/list.html
{% extends 'base/base.html' %}

{% block principal %}
<table id="example" class="table table-bordered datatable dataTable" width="100%">
        <thead>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Proyecto</th>
                <th>Cliente</th>
                <th>Asesor</th>
                <th>Fecha Inicial</th>
                <th>Fecha Entrega Diseño</th>
                <th>Fecha Entrega Muestras</th>
                <th>Tipo de Proyecto</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Proyecto</th>
                <th>Cliente</th>
                <th>Asesor</th>
                <th>Fecha Inicial</th>
                <th>Fecha Entrega Diseño</th>
                <th>Fecha Entrega Muestras</th>
                <th>Tipo de Proyecto</th>
                <th>Acción</th>
            </tr>
        </tfoot>
        <tbody>
        	{% for x in p%}
            <tr>  
                <td>{{x.id}}</td>
                <td>{{x.descripcion}}</td>
                <td>{{x.nombreCliente}}</td>
                <td>{{x.asesor}}</td>
                <td>{{x.fecha}}</td>
                <td>{{x.fechaEntDis}}</td>
                <td>{{x.fechaMueFis}}</td>
                <td>{{x.tipoProyecto}}</td>
                <td><a href="{% url 'pyc:proyecto_edit' x.id %}">editar</a></td>  
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
<script>
	$(document).ready(function() {
    	$('#example').DataTable();

	} );
</script>