apps/proyecto/urls.py
from django.conf.urls import url
from apps.proyecto.views import create_disenos, producto_edit, pru, proyecto_view, proyecto_home, proyecto_list,proyecto_edit, inicio, producto_proyecto, solicitud
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^$', login_required(proyecto_view), name='proyecto_view'),
	url(r'^home/', login_required(proyecto_home), name='proyecto_home'),
	url(r'^list$', login_required(proyecto_list), name='proyecto_list'),
	url(r'^editar/(?P<id_proyecto>\d+)/$', login_required(proyecto_edit), name='proyecto_edit'),
	url(r'^inicio/', login_required(inicio), name='inicio'),
	url(r'^prueba/$', login_required(producto_proyecto), name='producto_proyecto'),
	url(r'^pru/(?P<id_proyecto>\d+)/(?P<id_producto>\d+)/$', login_required(pru), name='pru'),
	url(r'^ediproducto/(?P<id_producto>\d+)/$', login_required(producto_edit), name='producto_edit'),
	url(r'^solicitarcliente/$', login_required(solicitud), name='solicitud'),
	url(r'^diseños/$', login_required(create_disenos), name='create_disenos'),
]

apps/usuarios/urls.py
from django.conf.urls import url
from apps.usuarios.views import RegistroUsuario, index, recuperar

urlpatterns = [
	url(r'^registrar/', RegistroUsuario.as_view(), name="registro"),
	url(r'^completado/', index, name='index'),
	url(r'^recuperar/', recuperar, name='recuperar'),
]

intigroup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^adminInti/', admin.site.urls),
    url(r'^proyecto/', include('apps.proyecto.urls', namespace="pyc")),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usu")),
    url(r'^diseno/', include('apps.diseno.urls', namespace="dis")),
    url(r'^$', login, {'template_name':'index.html'}, name="login"),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout', logout_then_login, name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/LoginI.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Nombre de usuario:</label>
                <input class="form-control" type="text" name="username">
           </div>
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Contraseña:</label>
                <input class="form-control" type="password" name="password">
           </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Ingresar">
           </div>
        </div>
    </div>
    </form>
{% endblock %}

templates/index.html
{% extends 'base/base.html' %}

{% block content %}

{% if request.user.is_authenticated %}

<div class="page-body login-page login-form-fall">

<div class="login-container">
    
    <div class="login-header login-caret">
        
        <div class="login-content">
            <br/><br/>
                {% load staticfiles  %}
                <img src="{% static 'img/logo_inti.png' %}" width="220" alt="" />            
        </div>
        
    </div>
    
    <div class="login-progressbar">
        <div></div>
    </div>
    
    <div class="login-form">
        
        <div class="login-content">
            <h1>Ya ingresaste a la aplicación</h1>
            <a href="{% url 'pyc:inicio'%}"><p>Volver al inicio</p></a>            
        </div>
        
    </div>
    
</div>

{% else %}



<div class="page-body login-page login-form-fall">

<div class="login-container">
    
    <div class="login-header login-caret">
        
        <div class="login-content">
            <br/><br/>
                {% load staticfiles  %}
                <img src="{% static 'img/logo_inti.png' %}" width="220" alt="" />
            
            
            <p class="description">Por favor ingrese su usuario y contraseña</p>
            
            <!-- progress bar indicator -->
            <div class="login-progressbar-indicator">
                <h3>43%</h3>
                <span>Ingresando...</span>
            </div>
        </div>
        
    </div>
    
    <div class="login-progressbar">
        <div></div>
    </div>
    
    <div class="login-form">
        
        <div class="login-content">
            <!--mensaje de error... configurar-->
            <div class="form-login-error">
                <h3>Error de autenticación</h3>
                <p>Ingrese nuevamente usuario y contraseña</p>
            </div>
            
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="entypo-user"></i>
                        </div>
                        
                        <input type="text" class="form-control" name="username" placeholder="Usuario" autocomplete="off" />
                    </div>
                    
                </div>
                
                <div class="form-group">
                    
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="entypo-key"></i>
                        </div>
                        
                        <input type="password" class="form-control" name="password" placeholder="Contraseña" autocomplete="off" />
                    </div>
                
                </div>
                
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-login" style="width:100%">
                        <i class="entypo-login"></i>
                        Ingresar
                    </button>
                </div>
                <p><a href="{% url 'usu:recuperar' %}">¿Olvidaste tu contraseña?</a></p>
                <p>¿Aún no tienes cuenta?<a href="{% url 'usu:registro' %}">Regístrate aquí</a></p>                
            </form>
            
        </div>
        
    </div>
    
</div>

{% endif %}

{% endblock %}