apps/diseno/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.diseno.views import inicio_dis, diseno_proyecto, diseno_producto


urlpatterns = [
	url(r'^$', login_required(inicio_dis), name='inicio_dis'),
	url(r'^proyectos/', login_required(diseno_proyecto), name='diseno_proyecto'),
	url(r'^productos/$', diseno_producto, name='diseno_producto'),
	# url(r'^editar/(?P<id_proyecto>\d+)/$', proyecto_edit, name='proyecto_edit'),
	# url(r'^inicio/', login_required(inicio), name='inicio'),
]

apps/proyecto/urls.py
from django.conf.urls import url
from apps.proyecto.views import create_disenos, producto_edit, pru, proyecto_view, proyecto_home, proyecto_list,proyecto_edit, inicio, producto_proyecto, solicitud
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^$', login_required(proyecto_view), name='proyecto_view'),
	url(r'^home/', login_required(proyecto_home), name='proyecto_home'),
	url(r'^list$', login_required(proyecto_list), name='proyecto_list'),
	url(r'^editar/(?P<id_proyecto>\d+)/$', login_required(proyecto_edit), name='proyecto_edit'),
	url(r'^inicio/', login_required(inicio), name='inicio'),
	url(r'^prueba/$', login_required(producto_proyecto), name='producto_proyecto'),
	url(r'^pru/(?P<id_proyecto>\d+)/(?P<id_producto>\d+)/$', login_required(pru), name='pru'),
	url(r'^ediproducto/(?P<id_producto>\d+)/$', login_required(producto_edit), name='producto_edit'),
	url(r'^solicitarcliente/$', login_required(solicitud), name='solicitud'),
	url(r'^diseños/$', login_required(create_disenos), name='create_disenos'),
]

intigroup/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^adminInti/', admin.site.urls),
    url(r'^proyecto/', include('apps.proyecto.urls', namespace="pyc")),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace="usu")),
    url(r'^diseno/', include('apps.diseno.urls', namespace="dis")),
    url(r'^$', login, {'template_name':'index.html'}, name="login"),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name="login"),
    url(r'^logout', logout_then_login, name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/diseno/models.py
from django.db import models
from apps.proyecto.models import proyecto

# Create your models here.
class disenadores(models.Model):
	nombre = models.CharField(max_length=30)

	def __str__(self):
		return self.nombre

class acabadosGalvanico(models.Model):
	nombre = models.CharField(max_length=30)

	def __str__(self):
		return self.nombre

class materialesP(models.Model):
	nombre = models.CharField(max_length=20)

	def __str__(self):
		return self.nombre

class producto(models.Model):
	idProyecto = models.ForeignKey(proyecto, on_delete=models.CASCADE, blank=True, null=True)
	nombre = models.CharField(max_length=30, blank=True, null=True)
	presupuesto = models.CharField(max_length=10, blank=True, null=True, default=0)
	unidades = models.CharField(max_length=10, blank=True, null=True, default=0)
	total = models.CharField(max_length=30, blank=True, null=True, default=0)
	muestraF = models.CharField(max_length=3, blank=True, null=True)
	numeroP = models.CharField(max_length=2, blank=True, null=True)
	materiales = models.ManyToManyField(materialesP, blank=True)
	acabados = models.ManyToManyField(acabadosGalvanico, blank=True) 
	descripcionP = models.CharField(max_length=200, blank=True, null=True)
	insumosD = models.CharField(max_length=200, blank=True, null=True)
	empaque = models.CharField(max_length=200, blank=True, null=True)
	disenador = models.ForeignKey(disenadores, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return	self.nombre

class diseno(models.Model):
	idProducto = models.ForeignKey(producto, on_delete=models.CASCADE, blank=True, null=True)
	nombre = models.CharField(max_length=40)

	def __str__(self):
		return self.nombre

apps/diseno/forms.py
from django import forms
from apps.diseno.models import producto, diseno
from apps.proyecto.models import *

class productoForm(forms.ModelForm):

	class Meta:

		model = producto
		fields = ('idProyecto', 'nombre', 'presupuesto', 'unidades', 'total', 'muestraF', 'numeroP', 'materiales', 'acabados', 'descripcionP', 'insumosD', 'empaque', 'disenador')
		widgets = {
			'idProyecto': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'idProyecto', 'style': 'display:none;' }),
			'nombre': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'nombre', 'style': 'display:none;' }),
			'presupuesto': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Presupuesto del producto'}),
			'unidades': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Unidades del producto'}),
			'total': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Valor total del producto'}),
			'muestraF': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'muestraF'}),
			'numeroP': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'numeroP'}),
			'materiales': forms.CheckboxSelectMultiple({'class':'form-control col-md-9'}),
			'acabados': forms.CheckboxSelectMultiple({'class':'form-control'}),
			'descripcionP': forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Describa el producto'}),
			'insumosD':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Mencione los insumos decorativos'}),
			'empaque':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Describa los empaques del proyecto'}),
		}

class disenoForm(forms.ModelForm):

	class Meta:

		model = diseno
		fields = ('__all__')

apps/diseno/views.py
from django.shortcuts import render
from apps.proyecto.models import item, proyecto
from apps.diseno.models import producto

i = item.objects.all()

# Create your views here.
def inicio_dis(request):
	return render(request, 'diseno/inicio.html', {'i':i})

def diseno_proyecto(request):
	p = proyecto.objects.all()
	return render(request, 'diseno/verProyecto.html', {'i':i, 'p':p})

def diseno_producto(request):
	pro = producto.objects.all()
	return render(request, 'diseno/verProducto.html', {'i':i, 'pro':pro})

templates/diseno/inicio.html
{% extends 'base/base.html' %}

{% block principal %}
		<div class="row">
			<a href="{% url 'dis:diseno_proyecto' %}">
			<div class="col-sm-3 col-xs-6">
		
				<div class="tile-stats tile-primary">
					<div class="icon"><i class="entypo-clipboard"></i></div>
					<div class="num" data-start="0" data-end="{{c}}" data-postfix="" data-duration="2500" data-delay="0">0</div>
		
					<h3>Ver Proyectos</h3>
					<p>Se visualizan todos los proyectos creados</p>
				</div>
		
			</div>
			</a>
			
			<a href="{% url 'dis:diseno_producto' %}">
			<div class="col-sm-3 col-xs-6">
		
				<div class="tile-stats tile-blue">
					<div class="icon"><i class="entypo-list-add"></i></div>
					<div class="num" data-start="0" data-end="{{c}}" data-postfix="" data-duration="1500" data-delay="600">0</div>
		
					<h3>Ver Productos</h3>
					<p>Permite la edición de proyectos creados.</p>
				</div>
		
			</div>
			</a>
		
		</div>
{% endblock %}

templates/diseno/verProducto.html
{% extends 'base/base.html' %}

{% block principal %}

<div class = "panel-heading">
    

<table id="example" class="table table-bordered datatable dataTable" width="100%">
        <thead>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Producto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Producto</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
        	{% for x in pro %}
            <tr>  
                <td>{{x.idProyecto}}</td>
                <td>{{x.nombre}}</td>
                <td><a href="{% url 'pyc:producto_edit' x.id %}">editar</a></td>  
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
<script>
	$(document).ready(function() {
        $('#example').DataTable();
	} );
</script>

templates/diseno/verProyecto.html
{% extends 'base/base.html' %}

{% block principal %}
<table id="example" class="table table-bordered datatable dataTable" width="100%">
        <thead>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Proyecto</th>
                <th>Cliente</th>
                <th>Asesor</th>
                <th>Fecha Inicial</th>
                <th>Fecha Entrega Diseño</th>
                <th>Fecha Entrega Muestras</th>
                <th>Tipo de Proyecto</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>IdProyecto</th>
                <th>Nombre Proyecto</th>
                <th>Cliente</th>
                <th>Asesor</th>
                <th>Fecha Inicial</th>
                <th>Fecha Entrega Diseño</th>
                <th>Fecha Entrega Muestras</th>
                <th>Tipo de Proyecto</th>
                <th>Acción</th>
            </tr>
        </tfoot>
        <tbody>
        	{% for x in p%}
            <tr>  
                <td>{{x.id}}</td>
                <td>{{x.descripcion}}</td>
                <td>{{x.nombreCliente}}</td>
                <td>{{x.asesor}}</td>
                <td>{{x.fecha}}</td>
                <td>{{x.fechaEntDis}}</td>
                <td>{{x.fechaMueFis}}</td>
                <td>{{x.tipoProyecto}}</td>
                <td><a href="{% url 'pyc:proyecto_edit' x.id %}">
                editar </a><button type="button" data-toggle="modal" data-target="#myModal">Asignación diseñador</button></td>  
            </tr>
            {% endfor %}
        </tbody>
    </table>

<!-- Trigger the modal with a button 
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" aria-label="Help"><span class="glyphicon glyphicon-flash"></span></button>-->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Asignación de diseño al producto {{a}}</h4>
      </div>
      <div class="modal-body">
        {% for d in dise %}
            <ul>
                <li>{{d.nombre}}</li>
            </ul>
        {% endfor %}
        <hr/>
        <form method='post' action="{% url 'pyc:create_disenos'%}">{% csrf_token %}
            {{disForm}}
            <input type="submit">
        </form>
        <hr/>
    </div>
</div>
<div>
    
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}
<script>
	$(document).ready(function() {
    	$('#example').DataTable();
	} );
</script>